# Generated by Django 4.2.2 on 2023-08-30 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FedsqApp', '0003_alter_usuario_rut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plato',
            name='id_ingrediente',
        ),
        migrations.AddField(
            model_name='plato',
            name='ingredientes',
            field=models.ManyToManyField(to='FedsqApp.ingrediente'),
        ),
    ]
